project:
  type: website
  output-dir: .

website:
  google-analytics: "G-JBWPRMFXM3"
  title: "Klara Weinhappl"
  # favicon: "FP_logo.png"
  navbar:
    background: light
#     right:
#       - blog.qmd
 #     - icon: twitter
   #   - text: CV
    #    href: CV/CV_FP.pdf
  

page-footer:
    # background: default # or dark
    left:
      - "Copyright 2025, Klara Weinhappl"
        
format:
  html:
    theme: default
    css: styles.css
    
grid:
     body-width: 1000px       
     margin-width: 50px



editor: visual

